kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: dev-eol1
  Name: odo-api
  Url:
  - Name: odo-api-8080
    Port: 8080
    Secure: true
